FROM node:18-alpine3.17 AS build

# Purpose of phase 1 is to build the SvelteKit app using Vite.. need full npm install for dev/build dependencies
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# Purpose of phase 2 is to build the production image
FROM node:18-alpine3.17 AS deploy
WORKDIR /app
RUN rm -rf ./*

# Install only production dependencies
COPY --from=build /app/package.json .
RUN npm install --omit=dev

# copying over the SvelteKit app into the production build
RUN mkdir -p ./build
RUN chmod -R 777 ./build
COPY --from=build /app/build ./build

# Copy over dependencnies kept outside the app subfolder
COPY ./tenants.yaml .
COPY ./static ./static

EXPOSE 3000

CMD ["node","build/index.js"]
